### ISSUE TITLE
some gestures not working

### ISSUE THREAD

**Issue by xxesth** [NayamAmarshe/ToucheggKDE#17]
hi,

i can only do 2 gestures:
3 fingers swipe down: show desktop/ present windows if already showing desktop
3 fingers left/right: switch to left/right virtual desktop

i would appreciate any kind of help.
thanks.

version: kde plasma 6.2.4, arch linux.

**Comment by fwinn** [comment]
Try replacing all `qdbus` commands with `qdbus6`

**Comment by xxesth** [comment]
some functions are working at the moment, thanks!
