### ISSUE TITLE
Expose and desktop grid shortcut not working

### ISSUE THREAD

**Issue by SuitedBadge401** [NayamAmarshe/ToucheggKDE#3]
Hi, the Kwin expose and desktop grid shortcuts aren't working on my machine. I'm running OpenSUSE Tumbleweed (Plasma 5.22) and Touchegg v2.0.11.

**Comment by SuitedBadge401** [comment]
UPDATE: Missing the qdbus package. Will update if I've fixed my issue.

**Comment by SuitedBadge401** [comment]
UPDATE: Solved! The command is actually `qdbus-qt5 org.kde.kglobalaccel /component/kwin invokeShortcut 'Expose'`

As you can see it's `qdbus-qt5`, not simply `qdbus`. This depends on the distro I think, since the original worked fine on Fedora. Maybe consider adding it to the code?

**Comment by NayamAmarshe** [comment]
> UPDATE: Solved! The command is actually `qdbus-qt5 org.kde.kglobalaccel /component/kwin invokeShortcut 'Expose'`
> 
> As you can see it's `qdbus-qt5`, not simply `qdbus`. This depends on the distro I think, since the original worked fine on Fedora. Maybe consider adding it to the code?

Hmm, maybe I can add an instruction to alias qdbus-qt5 as qdbus? On KDE Neon, Kubuntu and many other distros, the command is `qdbus` and there's no `-qt-5`

**Comment by SuitedBadge401** [comment]
> > UPDATE: Solved! The command is actually `qdbus-qt5 org.kde.kglobalaccel /component/kwin invokeShortcut 'Expose'`
> > As you can see it's `qdbus-qt5`, not simply `qdbus`. This depends on the distro I think, since the original worked fine on Fedora. Maybe consider adding it to the code?
> 
> Hmm, maybe I can add an instruction to alias qdbus-qt5 as qdbus? On KDE Neon, Kubuntu and many other distros, the command is `qdbus` and there's no `-qt-5`

That's certainly a very good idea. That would probably be the most elegant solution.
