### ISSUE TITLE
"Swipe 3 Finger Left/Right" does two job

### ISSUE THREAD

**Issue by ybgirgin3** [NayamAmarshe/ToucheggKDE#4]
Swiping 3 finger left makes me go next virtual desktop that's okay. And swiping 3 finger right makes me go previous virtual desktop but in the momenth that I switched the previous desktop, google chrome goes previous page too

How to solve it

**Comment by NayamAmarshe** [comment]
That shouldn't be happening, you should check your virtual desktop settings.
