### ISSUE TITLE
it doesn't seem to work on Manjaro

### ISSUE THREAD

**Issue by Arrow-x** [NayamAmarshe/ToucheggKDE#5]
KDE Plasma version 5.22.4
KDE Frameworks Version 5.85.0
QT Version 5.15.2
Kernel Version 5.13.11-1-MANJARO 64bit 

so the regular gestures work (two fingers tap for right click, swap for scrolling ...etc)
but this doesn't work, touchegg is running and the config is applied

**Comment by NayamAmarshe** [comment]
> KDE Plasma version 5.22.4
> KDE Frameworks Version 5.85.0
> QT Version 5.15.2
> Kernel Version 5.13.11-1-MANJARO 64bit
> 
> so the regular gestures work (two fingers tap for right click, swap for scrolling ...etc)
> but this doesn't work, touchegg is running and the config is applied

Are you on wayland?

**Comment by Arrow-x** [comment]
no, 
I installed wayland later, and doesn't work there either

**Comment by NayamAmarshe** [comment]
> no,
> I installed wayland later, and doesn't work there either

Are you sure you're using libinput drivers?

**Comment by Arrow-x** [comment]
yes, $ libinput list-devices does show my trackpad

**Comment by NayamAmarshe** [comment]
> yes, $ libinput list-devices does show my trackpad

Then I suppose the issue should be raised in https://github.com/JoseExposito/touchegg
I'm sure they'll know what's wrong.

**Comment by NayamAmarshe** [comment]
Closing issue as not related to TouchEggKDE
