### ISSUE TITLE
Doesn't work at all for Kubuntu 21.04

### ISSUE THREAD

**Issue by rastacalavera** [NayamAmarshe/ToucheggKDE#7]
Just found out about this project! I use to use [Fusuma](https://github.com/iberianpig/fusuma) and got excited when I found this. I followed the directions for installation and restarted my computer when the gestures did not function as expected. After restart, they still did not work.
Hoping that someone can help me trouble shoot it. My machine details are below:

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-40-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
Memory: 29.3 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 3 Graphics

Addition:
rastacalavera@M141:~$ touchegg
Reading config from  "/home/rastacalavera/.config/touchegg/touchegg.conf"
Try to make a multitouch gesture. If everything goes well the information about the gesture must appear
[+] Avaliable gesture:
         Name ->  Flick
[+] Avaliable gesture:
         Name ->  Drag
[+] Avaliable gesture:
         Name ->  Pinch
[+] Avaliable gesture:
         Name ->  Rotate
[+] Avaliable gesture:
         Name ->  Tap
[+] Avaliable gesture:
         Name ->  Touch

**Comment by NayamAmarshe** [comment]
This seems more of an issue with Touchegg than this repository which only serves a config.
Please create an issue ticket on Touchegg repository, they might be able to help you better than I can :)
